language: nix

os:
  - linux
  - osx

env:
  - EMACS_CI=emacs-25-1
  - EMACS_CI=emacs-25-2
  - EMACS_CI=emacs-25-3
  - EMACS_CI=emacs-26-1
  - EMACS_CI=emacs-26-2
  - EMACS_CI=emacs-26-3
  - EMACS_CI=emacs-snapshot

before_install:
  # nix-emacs-ci
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)

  # cask
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH=$HOME/.cask/bin:$PATH

install:
  - make install

script:
  - emacs --version
  - make test
